/* airlines-meta.js — 全106社の航空会社メタデータ共有モジュール（非 ESM / <script src> 規約）
 * SSOT: この配列が world-airlines.html と index.html（サラリーエンジンのピッカー）で共有される。
 * 二重持ちしないこと。数値(salary文字列)は表示用の概算ラベルで、給与の正は salary-data.json。
 * shape: {code,name,en,region,color,salary,file,flag,type,taxfree,alliance}
 */
(function (w) {
  'use strict';
  var AIRLINES = [
{code:'ANA', name:'全日本空輸（ANA）',         en:'All Nippon Airways',    region:'japan',  color:'#1A6EB5',salary:'¥2,700万',file:'airlines/ana.html',fleet:'nw',      flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'JAL', name:'日本航空（JAL）',           en:'Japan Airlines',        region:'japan',  color:'#CC0000',salary:'¥2,700万',file:'airlines/jal.html',fleet:'nw',      flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'SKY', name:'スカイマーク',             en:'Skymark Airlines',      region:'japan',  color:'#00A2E8',salary:'¥1,900万',file:'airlines/skymark.html',fleet:'n',  flag:'🇯🇵',type:'lcc',taxfree:false,alliance:''},
{code:'ZIP', name:'ZIPAIR Tokyo',             en:'ZIPAIR Tokyo',          region:'japan',  color:'#00C48C',salary:'¥2,500万',file:'airlines/zipair.html',fleet:'w',   flag:'🇯🇵',type:'lcc',taxfree:false,alliance:''},
{code:'APJ', name:'Peach Aviation',           en:'Peach Aviation',        region:'japan',  color:'#E5007F',salary:'¥2,350万',file:'airlines/peach.html',fleet:'n',    flag:'🇯🇵',type:'lcc',taxfree:false,alliance:''},
{code:'GK',  name:'ジェットスター・ジャパン', en:'Jetstar Japan',         region:'japan',  color:'#FF5900',salary:'¥2,400万',file:'airlines/jetstar-japan.html',fleet:'n',flag:'🇯🇵',type:'lcc',taxfree:false,alliance:''},
{code:'IJ',  name:'スプリング・ジャパン',     en:'Spring Japan',          region:'japan',  color:'#FF6B00',salary:'¥2,000万',file:'airlines/spring-japan.html',fleet:'n',flag:'🇯🇵',type:'lcc',taxfree:false,alliance:''},
{code:'XM',  name:'ジェイエア（J-AIR）',      en:'J-AIR',                 region:'japan',  color:'#CC0000',salary:'¥2,000万',file:'airlines/j-air.html',fleet:'r',    flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'JALグループ'},
{code:'NU',  name:'日本トランスオーシャン航空（JTA）',en:'Japan Transocean Air',region:'japan',color:'#CC0000',salary:'¥2,000万',file:'airlines/jta.html',fleet:'n',flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'JALグループ'},
{code:'3H',  name:'日本エアコミューター（JAC）',en:'Japan Air Commuter',  region:'japan',  color:'#CC0000',salary:'¥1,700万',file:'airlines/jac.html',fleet:'r',      flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'JALグループ'},
{code:'3G',  name:'琉球エアーコミューター（RAC）',en:'Ryukyu Air Commuter',region:'japan', color:'#CC0000',salary:'¥1,700万',file:'airlines/rac.html',fleet:'r',      flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'JALグループ'},
{code:'NTH', name:'北海道エアシステム（HAC）', en:'Hokkaido Air System',  region:'japan',  color:'#CC0000',salary:'¥1,700万',file:'airlines/hac.html',fleet:'r',      flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'JALグループ'},
{code:'EH',  name:'ANAウイングス',            en:'ANA Wings',            region:'japan',  color:'#1A6EB5',salary:'¥2,000万',file:'airlines/ana-wings.html',fleet:'rn',flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ANAグループ'},
{code:'NQ',  name:'AirJapan',                 en:'AirJapan',             region:'japan',  color:'#0090CC',salary:'¥2,100万',file:'airlines/airjapan.html',fleet:'w', flag:'🇯🇵',type:'lcc',taxfree:false,alliance:'ANAグループ'},
{code:'HD',  name:'AIRDO',                    en:'AIRDO',                region:'japan',  color:'#0055A4',salary:'¥1,950万',file:'airlines/airdo.html',fleet:'nw',    flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ANA提携'},
{code:'6J',  name:'ソラシドエア',             en:'Solaseed Air',         region:'japan',  color:'#009EDB',salary:'¥2,000万',file:'airlines/solaseed.html',fleet:'n', flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ANA提携'},
{code:'7G',  name:'スターフライヤー',         en:'StarFlyer',            region:'japan',  color:'#1C1C3A',salary:'¥1,950万',file:'airlines/starflyer.html',fleet:'n',flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ANA提携'},
{code:'JH',  name:'フジドリームエアラインズ（FDA）',en:'Fuji Dream Airlines',region:'japan',color:'#FF6600',salary:'¥1,600万',file:'airlines/fda.html',fleet:'r',  flag:'🇯🇵',type:'fsc',taxfree:false,alliance:''},
{code:'FW',  name:'アイベックスエアラインズ（IBEX）',en:'IBEX Airlines', region:'japan',  color:'#0033A0',salary:'¥1,700万',file:'airlines/ibex.html',fleet:'r',     flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ANA提携'},
{code:'JO',  name:'トキエア',                 en:'Toki Air',             region:'japan',  color:'#00A0C6',salary:'¥1,400万',file:'airlines/toki-air.html',fleet:'r', flag:'🇯🇵',type:'fsc',taxfree:false,alliance:''},
{code:'OC',  name:'オリエンタルエアブリッジ（ORC）',en:'Oriental Air Bridge',region:'japan',color:'#1B4F97',salary:'¥1,500万',file:'airlines/orc.html',fleet:'r',  flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'ANA提携'},
{code:'MZ',  name:'天草エアライン（AMX）',    en:'Amakusa Airlines',     region:'japan',  color:'#00843D',salary:'¥1,400万',file:'airlines/amx.html',fleet:'r',      flag:'🇯🇵',type:'fsc',taxfree:false,alliance:'JAL/ANA提携'},
{code:'SCA', name:'新中央航空',               en:'Shin Central Air',     region:'japan',  color:'#003087',salary:'¥1,250万',file:'airlines/shin-central.html',fleet:'r',flag:'🇯🇵',type:'fsc',taxfree:false,alliance:''},
{code:'THK', name:'東邦航空',                 en:'Toho Air Service',     region:'japan',  color:'#CC6600',salary:'¥1,200万',file:'airlines/toho-air.html',fleet:'r', flag:'🇯🇵',type:'fsc',taxfree:false,alliance:''},
{code:'DAK', name:'第一航空',                 en:'Daiichi Aviation',     region:'japan',  color:'#0066CC',salary:'¥1,300万',file:'airlines/daiichi-air.html',fleet:'r',flag:'🇯🇵',type:'fsc',taxfree:false,alliance:''},
{code:'SNJ', name:'新日本航空',               en:'Shin Nihon Airlines',  region:'japan',  color:'#CC0033',salary:'¥1,200万',file:'airlines/shin-nihon.html',fleet:'r',flag:'🇯🇵',type:'fsc',taxfree:false,alliance:''},
{code:'KAL', name:'大韓航空',               en:'Korean Air',            region:'asia',  color:'#0032A0',salary:'¥2,450万',file:'airlines/korean-air.html',fleet:'nw',      flag:'🇰🇷',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'OZ',  name:'アシアナ航空',           en:'Asiana Airlines',       region:'asia',  color:'#E51820',salary:'¥2,180万',file:'airlines/asiana.html',fleet:'nw',          flag:'🇰🇷',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'EVA', name:'エバー航空',             en:'EVA Air',               region:'asia',  color:'#00A599',salary:'¥1,750万',file:'airlines/eva-air.html',fleet:'nw',          flag:'🇹🇼',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'CAL', name:'チャイナエアライン',     en:'China Airlines',        region:'asia',  color:'#D00027',salary:'¥2,000万',file:'airlines/china-airlines.html',fleet:'nw',   flag:'🇹🇼',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'JX',  name:'スターラックス',         en:'StarLux Airlines',      region:'asia',  color:'#007A9B',salary:'¥2,800万',file:'airlines/starlux.html',fleet:'nw',          flag:'🇹🇼',type:'fsc',taxfree:false,alliance:''},
{code:'TG',  name:'タイ国際航空',           en:'Thai Airways',          region:'asia',  color:'#4A0A77',salary:'¥1,850万',file:'airlines/thai-airways.html',fleet:'w',     flag:'🇹🇭',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'MH',  name:'マレーシア航空',         en:'Malaysia Airlines',     region:'asia',  color:'#CC0000',salary:'¥1,900万',file:'airlines/malaysia-airlines.html',fleet:'nw',flag:'🇲🇾',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'GA',  name:'ガルーダ・インドネシア', en:'Garuda Indonesia',      region:'asia',  color:'#0044A8',salary:'¥1,500万',file:'airlines/garuda-indonesia.html',fleet:'nw', flag:'🇮🇩',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'VN',  name:'ベトナム航空',           en:'Vietnam Airlines',      region:'asia',  color:'#006B4F',salary:'¥1,900万',file:'airlines/vietnam-airlines.html',fleet:'nw', flag:'🇻🇳',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'PR',  name:'フィリピン航空',         en:'Philippine Airlines',   region:'asia',  color:'#0038A8',salary:'¥1,550万',file:'airlines/philippine-airlines.html',fleet:'nw',flag:'🇵🇭',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'AK',  name:'エアアジア',             en:'AirAsia',               region:'asia',  color:'#FF0000',salary:'¥1,300万',file:'airlines/airasia.html',fleet:'n',          flag:'🇲🇾',type:'lcc',taxfree:false,alliance:''},
{code:'TR',  name:'スクート',               en:'Scoot',                 region:'asia',  color:'#FBD800',salary:'¥2,350万',file:'airlines/scoot.html',fleet:'nw',            flag:'🇸🇬',type:'lcc',taxfree:false,alliance:''},
{code:'6E',  name:'インディゴ',             en:'IndiGo',                region:'asia',  color:'#006DB7',salary:'¥1,600万',file:'airlines/indigo.html',fleet:'n',           flag:'🇮🇳',type:'lcc',taxfree:false,alliance:''},
{code:'AI',  name:'エア・インディア',       en:'Air India',             region:'asia',  color:'#C8102E',salary:'¥1,550万',file:'airlines/air-india.html',fleet:'nw',        flag:'🇮🇳',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'CA',  name:'中国国際航空',           en:'Air China',             region:'asia',  color:'#C00000',salary:'¥3,050万',file:'airlines/air-china.html',fleet:'nw',        flag:'🇨🇳',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'CZ',  name:'中国南方航空',           en:'China Southern',        region:'asia',  color:'#005BAC',salary:'¥2,950万',file:'airlines/china-southern.html',fleet:'nw',   flag:'🇨🇳',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'MU',  name:'中国東方航空',           en:'China Eastern',         region:'asia',  color:'#CC0000',salary:'¥2,900万',file:'airlines/china-eastern.html',fleet:'nw',    flag:'🇨🇳',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'HU',  name:'海南航空',               en:'Hainan Airlines',       region:'asia',  color:'#003087',salary:'¥3,050万',file:'airlines/hainan-airlines.html',fleet:'nw',  flag:'🇨🇳',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'VJ',  name:'ベトジェット',           en:'VietJet Air',           region:'asia',  color:'#D62829',salary:'¥1,800万', file:'airlines/vietjet.html',fleet:'n',           flag:'🇻🇳',type:'lcc',taxfree:false,alliance:''},
{code:'QH',  name:'バンブー・エアウェイズ', en:'Bamboo Airways',        region:'asia',  color:'#00A651',salary:'¥1,850万',file:'airlines/bamboo-airways.html',fleet:'nw',   flag:'🇻🇳',type:'lcc',taxfree:false,alliance:''},
{code:'UO',  name:'HKエクスプレス',         en:'HK Express',            region:'asia',  color:'#E20074',salary:'¥2,050万',file:'airlines/hong-kong-express.html',fleet:'n',flag:'🇭🇰',type:'lcc',taxfree:false,alliance:''},
{code:'ID',  name:'バティック・エア',       en:'Batik Air',             region:'asia',  color:'#FF6B00',salary:'¥880万',file:'airlines/batik-air.html',fleet:'n',        flag:'🇮🇩',type:'lcc',taxfree:false,alliance:''},
{code:'BI',  name:'ロイヤル・ブルネイ',     en:'Royal Brunei',          region:'asia',  color:'#C8102E',salary:'¥2,050万',file:'airlines/royal-brunei.html',fleet:'nw',     flag:'🇧🇳',type:'fsc',taxfree:true, alliance:''},
{code:'SQ',  name:'シンガポール航空',       en:'Singapore Airlines',    region:'asia',  color:'#00378B',salary:'¥3,400万',file:'airlines/singapore-airlines.html',fleet:'nw',flag:'🇸🇬',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'CX',  name:'キャセイパシフィック',   en:'Cathay Pacific',        region:'asia',  color:'#006564',salary:'¥3,600万',file:'airlines/cathay-pacific.html',fleet:'nw',   flag:'🇭🇰',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'EK',  name:'エミレーツ',             en:'Emirates',              region:'mideast',color:'#D4002B',salary:'¥3,700万',file:'airlines/emirates.html',fleet:'w',         flag:'🇦🇪',type:'fsc',taxfree:true, alliance:''},
{code:'QR',  name:'カタール航空',           en:'Qatar Airways',         region:'mideast',color:'#5C0632',salary:'¥2,900万',file:'airlines/qatar-airways.html',fleet:'nw',    flag:'🇶🇦',type:'fsc',taxfree:true, alliance:'ワンワールド'},
{code:'EY',  name:'エティハド航空',         en:'Etihad Airways',        region:'mideast',color:'#B08D57',salary:'¥3,400万',file:'airlines/etihad.html',fleet:'nw',           flag:'🇦🇪',type:'fsc',taxfree:true, alliance:''},
{code:'RX',  name:'リヤドエアー',           en:'Riyadh Air',            region:'mideast',color:'#00B4D8',salary:'¥4,300万',file:'airlines/riyadh-air.html',fleet:'nw',       flag:'🇸🇦',type:'fsc',taxfree:true, alliance:''},
{code:'SV',  name:'サウディア',             en:'Saudia',                region:'mideast',color:'#1A7A4A',salary:'¥3,300万',file:'airlines/saudia.html',fleet:'nw',           flag:'🇸🇦',type:'fsc',taxfree:true, alliance:'スカイチーム'},
{code:'TK',  name:'ターキッシュ エアラインズ',en:'Turkish Airlines',    region:'mideast',color:'#C8102E',salary:'¥2,500万',file:'airlines/turkish-airlines.html',fleet:'nw', flag:'🇹🇷',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'WY',  name:'オマーン エア',          en:'Oman Air',              region:'mideast',color:'#C8102E',salary:'¥2,500万',file:'airlines/oman-air.html',fleet:'nw',         flag:'🇴🇲',type:'fsc',taxfree:true, alliance:''},
{code:'GF',  name:'ガルフ エア',            en:'Gulf Air',              region:'mideast',color:'#B8860B',salary:'¥2,700万',file:'airlines/gulf-air.html',fleet:'nw',         flag:'🇧🇭',type:'fsc',taxfree:true, alliance:''},
{code:'KU',  name:'クウェート航空',         en:'Kuwait Airways',        region:'mideast',color:'#007A3D',salary:'¥2,800万',file:'airlines/kuwait-airways.html',fleet:'nw',   flag:'🇰🇼',type:'fsc',taxfree:true, alliance:''},
{code:'RJ',  name:'ロイヤル ヨルダニアン',  en:'Royal Jordanian',       region:'mideast',color:'#9B111E',salary:'¥1,700万',file:'airlines/royal-jordanian.html',fleet:'nw',  flag:'🇯🇴',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'ET',  name:'エチオピア航空',         en:'Ethiopian Airlines',    region:'africa', color:'#EFC050',salary:'¥1,600万',file:'airlines/ethiopian-airlines.html',fleet:'nw',flag:'🇪🇹',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'SA',  name:'南アフリカ航空',         en:'South African Airways', region:'africa', color:'#006BA6',salary:'¥1,300万',file:'airlines/south-african-airways.html',fleet:'nw',flag:'🇿🇦',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'KQ',  name:'ケニア航空',             en:'Kenya Airways',         region:'africa', color:'#CC0000',salary:'¥1,500万',file:'airlines/kenya-airways.html',fleet:'nw',    flag:'🇰🇪',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'MS',  name:'エジプト航空',           en:'EgyptAir',              region:'africa', color:'#2F5597',salary:'¥1,550万',file:'airlines/egyptair.html',fleet:'nw',         flag:'🇪🇬',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'LH',  name:'ルフトハンザ',           en:'Lufthansa',             region:'eu_fsc', color:'#FEC10D',salary:'¥3,440万',file:'airlines/lufthansa.html',fleet:'nw',        flag:'🇩🇪',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'AF',  name:'エール フランス',        en:'Air France',            region:'eu_fsc', color:'#002395',salary:'¥3,530万',file:'airlines/air-france.html',fleet:'nw',       flag:'🇫🇷',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'KL',  name:'KLMオランダ航空',        en:'KLM',                   region:'eu_fsc', color:'#00A1DE',salary:'¥3,960万',file:'airlines/klm.html',fleet:'rnw',              flag:'🇳🇱',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'BA',  name:'ブリティッシュ エアウェイズ',en:'British Airways',   region:'eu_fsc', color:'#2B3E82',salary:'¥3,030万',file:'airlines/british-airways.html',fleet:'nw',  flag:'🇬🇧',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'VS',  name:'ヴァージン アトランティック',en:'Virgin Atlantic',   region:'eu_fsc', color:'#E2001A',salary:'¥3,600万',file:'airlines/virgin-atlantic.html',fleet:'w',  flag:'🇬🇧',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'LX',  name:'スイス インターナショナル',en:'SWISS',               region:'eu_fsc', color:'#E8122D',salary:'¥4,100万',file:'airlines/swiss.html',fleet:'nw',            flag:'🇨🇭',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'OS',  name:'オーストリア航空',       en:'Austrian Airlines',     region:'eu_fsc', color:'#CC0000',salary:'¥2,600万',file:'airlines/austrian.html',fleet:'nw',         flag:'🇦🇹',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'AY',  name:'フィンエアー',           en:'Finnair',               region:'eu_fsc', color:'#003580',salary:'¥3,000万',file:'airlines/finnair.html',fleet:'nw',          flag:'🇫🇮',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'SK',  name:'SAS スカンジナビア航空', en:'SAS',                   region:'eu_fsc', color:'#00445B',salary:'¥2,650万',file:'airlines/sas.html',fleet:'nw',              flag:'🇸🇪',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'IB',  name:'イベリア航空',           en:'Iberia',                region:'eu_fsc', color:'#CC0000',salary:'¥2,600万',file:'airlines/iberia.html',fleet:'nw',           flag:'🇪🇸',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'TP',  name:'TAPエア ポルトガル',     en:'TAP Air Portugal',      region:'eu_fsc', color:'#C0272D',salary:'¥2,240万',file:'airlines/tap.html',fleet:'nw',              flag:'🇵🇹',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'AZ',  name:'ITAエアウェイズ',        en:'ITA Airways',           region:'eu_fsc', color:'#008751',salary:'¥2,150万',file:'airlines/ita-airways.html',fleet:'nw',      flag:'🇮🇹',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'EI',  name:'エア リンガス',          en:'Aer Lingus',            region:'eu_fsc', color:'#00A84F',salary:'¥2,750万',file:'airlines/aer-lingus.html',fleet:'nw',       flag:'🇮🇪',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'LO',  name:'LOTポーランド航空',      en:'LOT Polish Airlines',   region:'eu_fsc', color:'#003399',salary:'¥1,400万',file:'airlines/lot.html',fleet:'rnw',              flag:'🇵🇱',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'A3',  name:'エーゲ航空',             en:'Aegean Airlines',       region:'eu_lcc', color:'#00539C',salary:'¥1,300万',file:'airlines/aegean.html',fleet:'n',           flag:'🇬🇷',type:'lcc',taxfree:false,alliance:'スターアライアンス'},
{code:'FI',  name:'アイスランド航空',       en:'Icelandair',            region:'eu_lcc', color:'#003087',salary:'¥2,150万',file:'airlines/icelandair.html',fleet:'nw',       flag:'🇮🇸',type:'lcc',taxfree:false,alliance:''},
{code:'DY',  name:'ノルウェー エア',        en:'Norwegian',             region:'eu_lcc', color:'#D41819',salary:'¥2,000万',file:'airlines/norwegian.html',fleet:'n',        flag:'🇳🇴',type:'lcc',taxfree:false,alliance:''},
{code:'FR',  name:'ライアンエアー',         en:'Ryanair',               region:'eu_lcc', color:'#073590',salary:'¥2,240万',file:'airlines/ryanair.html',fleet:'n',          flag:'🇮🇪',type:'lcc',taxfree:false,alliance:''},
{code:'U2',  name:'イージージェット',       en:'easyJet',               region:'eu_lcc', color:'#FF6600',salary:'¥2,700万',file:'airlines/easyjet.html',fleet:'n',          flag:'🇬🇧',type:'lcc',taxfree:false,alliance:''},
{code:'EW',  name:'ユーロウイングス',       en:'Eurowings',             region:'eu_lcc', color:'#8F174F',salary:'¥2,770万',file:'airlines/eurowings.html',fleet:'n',        flag:'🇩🇪',type:'lcc',taxfree:false,alliance:''},
{code:'VY',  name:'ヴエリング航空',         en:'Vueling',               region:'eu_lcc', color:'#FFCC00',salary:'¥1,720万',file:'airlines/vueling.html',fleet:'n',          flag:'🇪🇸',type:'lcc',taxfree:false,alliance:''},
{code:'W6',  name:'ウィズ エア',            en:'Wizz Air',              region:'eu_lcc', color:'#C6007E',salary:'¥2,400万',file:'airlines/wizz-air.html',fleet:'n',         flag:'🇭🇺',type:'lcc',taxfree:false,alliance:''},
{code:'DL',  name:'デルタ航空',             en:'Delta Air Lines',       region:'us',     color:'#C01933',salary:'¥6,160万',file:'airlines/delta.html',fleet:'nw',            flag:'🇺🇸',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'UA',  name:'ユナイテッド航空',       en:'United Airlines',       region:'us',     color:'#005DAA',salary:'¥6,320万',file:'airlines/united.html',fleet:'nw',           flag:'🇺🇸',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'AA',  name:'アメリカン航空',         en:'American Airlines',     region:'us',     color:'#0078D2',salary:'¥5,930万',file:'airlines/american.html',fleet:'nw',         flag:'🇺🇸',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'WN',  name:'サウスウエスト航空',     en:'Southwest Airlines',    region:'us',     color:'#FF7900',salary:'¥4,820万',file:'airlines/southwest.html',fleet:'n',        flag:'🇺🇸',type:'lcc',taxfree:false,alliance:''},
{code:'AS',  name:'アラスカ航空',           en:'Alaska Airlines',       region:'us',     color:'#0060AB',salary:'¥4,900万',file:'airlines/alaska-airlines.html',fleet:'n',  flag:'🇺🇸',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'B6',  name:'ジェットブルー航空',     en:'JetBlue',               region:'us',     color:'#003876',salary:'¥4,200万',file:'airlines/jetblue.html',fleet:'n',          flag:'🇺🇸',type:'lcc',taxfree:false,alliance:''},
{code:'NK',  name:'スピリット航空',         en:'Spirit Airlines',       region:'us',     color:'#FFD700',salary:'¥3,700万',file:'airlines/spirit.html',fleet:'n',           flag:'🇺🇸',type:'lcc',taxfree:false,alliance:''},
{code:'F9',  name:'フロンティア航空',       en:'Frontier Airlines',     region:'us',     color:'#00AE42',salary:'¥3,300万',file:'airlines/frontier.html',fleet:'n',         flag:'🇺🇸',type:'lcc',taxfree:false,alliance:''},
{code:'G4',  name:'アリジャント エアー',    en:'Allegiant Air',         region:'us',     color:'#F4A024',salary:'¥3,000万',file:'airlines/allegiant.html',fleet:'n',        flag:'🇺🇸',type:'lcc',taxfree:false,alliance:''},
{code:'AC',  name:'エア カナダ',            en:'Air Canada',            region:'us',     color:'#C8102E',salary:'¥3,360万',file:'airlines/air-canada.html',fleet:'nw',       flag:'🇨🇦',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'WS',  name:'ウエストジェット',       en:'WestJet',               region:'us',     color:'#00439C',salary:'¥3,400万',file:'airlines/westjet.html',fleet:'nw',          flag:'🇨🇦',type:'lcc',taxfree:false,alliance:''},
{code:'PD',  name:'ポーターエアラインズ',   en:'Porter Airlines',       region:'us',     color:'#3D1152',salary:'¥2,700万',file:'airlines/porter.html',fleet:'rn',           flag:'🇨🇦',type:'lcc',taxfree:false,alliance:''},
{code:'MX',  name:'ブリーズ エアウェイズ',  en:'Breeze Airways',        region:'us',     color:'#00B4D8',salary:'¥3,400万',file:'airlines/breeze-airways.html',fleet:'rn',   flag:'🇺🇸',type:'lcc',taxfree:false,alliance:''},
{code:'QF',  name:'カンタス航空',           en:'Qantas',                region:'oceania',color:'#EE0000',salary:'¥3,700万',file:'airlines/qantas.html',fleet:'nw',           flag:'🇦🇺',type:'fsc',taxfree:false,alliance:'ワンワールド'},
{code:'NZ',  name:'ニュージーランド航空',   en:'Air New Zealand',       region:'oceania',color:'#00539C',salary:'¥3,300万',file:'airlines/air-new-zealand.html',fleet:'rw',  flag:'🇳🇿',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'FJ',  name:'フィジー エアウェイズ',  en:'Fiji Airways',          region:'oceania',color:'#0073B0',salary:'¥1,700万',file:'airlines/fiji-airways.html',fleet:'nw',     flag:'🇫🇯',type:'fsc',taxfree:false,alliance:''},
{code:'JQ',  name:'ジェットスター エアウェイズ',en:'Jetstar Airways',   region:'oceania',color:'#FF5900',salary:'¥2,400万',file:'airlines/jetstar.html',fleet:'nw',          flag:'🇦🇺',type:'lcc',taxfree:false,alliance:''},
{code:'LA',  name:'ラタム航空',             en:'LATAM Airlines',        region:'latam',  color:'#E30613',salary:'¥1,900万',file:'airlines/latam.html',fleet:'nw',            flag:'🇨🇱',type:'fsc',taxfree:false,alliance:''},
{code:'AV',  name:'アビアンカ航空',         en:'Avianca',               region:'latam',  color:'#C60B1E',salary:'¥1,700万',file:'airlines/avianca.html',fleet:'n',          flag:'🇨🇴',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
{code:'AM',  name:'アエロメヒコ',           en:'Aeromexico',            region:'latam',  color:'#006CB7',salary:'¥2,300万',file:'airlines/aeromexico.html',fleet:'nw',       flag:'🇲🇽',type:'fsc',taxfree:false,alliance:'スカイチーム'},
{code:'CM',  name:'コパ航空',               en:'Copa Airlines',         region:'latam',  color:'#004A94',salary:'¥2,300万',file:'airlines/copa-airlines.html',fleet:'n',    flag:'🇵🇦',type:'fsc',taxfree:false,alliance:'スターアライアンス'},
  ];

  // file: 'airlines/ana.html' → 'ana'
  function slugOf(a) {
    return (a && a.file ? a.file : '').replace('airlines/', '').replace('.html', '');
  }

  w.PV_AIRLINES = AIRLINES;
  w.PV_slugOf = slugOf;
})(window);
